### PR TITLE
326 gallery fixes

### LINKED ISSUE #324: Can we have transition time on hover for cards?
image

### PR DESCRIPTION
**Pull request by patrickwieth**
this fixes #324 #325 and #326

### CODE REVIEW

File: src/components/elements/GalleryComponent.vue [hunk 1]
```diff
@@ -59,32 +71,32 @@ const cardIdsOnPage = computed(() => {
...
-
-
 onMounted(() => {
   state.cardsOnPage = props.cardsPerPage;
-  window.addEventListener("scroll", onScroll);
 });
 
+let loadButtonVisible = true;
+
+const loadyes = () => {
```
Comment (lxgr-linux) [inline src/components/elements/GalleryComponent.vue:94]: please not loadyes

Comment (patrickwieth) [reply src/components/elements/GalleryComponent.vue:94]: Shall we rename to loadYouLike()?

Comment (lxgr-linux) [reply src/components/elements/GalleryComponent.vue:94]: Please something propper
